



GET http://localhost:5198/books/501

### Create Book
POST http://localhost:5198/books
Content-Type: application/json

{
  "title": "Dune",
  "author": "Frank Herbert",
  "year": 1965
}


### Delete Book
DELETE http://localhost:5198/books/1
###

DELETE http://localhost:5198/books/9999


### Update Book

PUT http://localhost:5198/books/1
Content-Type: application/json

{
  "title": "Changes",
  "author": "David Bowie",
  "year": 1971
}
###

PUT http://localhost:5198/books/9999
Content-Type: application/json

{
  "title": "Unknown Book",
  "author": "Unknown Author",
  "year": 2000
}


### Get Book by Id
GET http://localhost:5198/books/1
###

GET http://localhost:5198/books/9999
###

### Get Books Page 1
GET http://localhost:5198/books?page=1&pageSize=10

### Get Books Page 2
GET http://localhost:5198/books?page=2&pageSize=10




### Get Members
GET http://localhost:5198/members

### Create Member
POST http://localhost:5198/members
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "email": "ada@example.com"
}

### Get Member Details
GET http://localhost:5198/members/1

### Update Member
PUT http://localhost:5198/members/1
Content-Type: application/json

{
  "name": "Ada Byron",
  "email": "ada.byron@example.com"
}

### Delete Member
DELETE http://localhost:5198/members/1

### Create member with credentials
POST http://localhost:5198/members
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "email": "ada@example.com",
  "password": "analytical-engine"
}

### Login
POST http://localhost:5198/auth/login
Content-Type: application/json

{
  "email": "ada@example.com",
  "password": "analytical-engine"
}
### Create administrator with credentials
POST http://localhost:5198/members
Content-Type: application/json

{
  "name": "Adamin Lovelace",
  "email": "admin@booktracker.local",
  "password": "development-admin-password"
}
### Login as administrator
POST http://localhost:5198/auth/login
Content-Type: application/json

{
  "email": "admin@booktracker.local",
  "password": "development-admin-password"
}

### Current member
GET http://localhost:5198/auth/me
Authorization: Bearer paste-token-here

###### Create book with token
POST http://localhost:5198/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQm9vayBUcmFja2VyIEFkbWluIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYWRtaW5AYm9va3RyYWNrZXIubG9jYWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzg0ODAxNTA2LCJpc3MiOiJCb29rVHJhY2tlciIsImF1ZCI6IkJvb2tUcmFja2VyIn0.kEgTRTo1_9bihfEU0OauJf57SZ3o1w3eChOd94xlaGk

  {
  "title": "Dune",
  "author": "Frank Herbert",
  "year": 1965
  }


### Administrator views members
GET http://localhost:5198/members
Authorization: Bearer paste-admin-token-here

### First update
PUT http://localhost:5198/books/501
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiQm9vayBUcmFja2VyIEFkbWluIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvZW1haWxhZGRyZXNzIjoiYWRtaW5AYm9va3RyYWNrZXIubG9jYWwiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJBZG1pbmlzdHJhdG9yIiwiZXhwIjoxNzg0ODAxNTA2LCJpc3MiOiJCb29rVHJhY2tlciIsImF1ZCI6IkJvb2tUcmFja2VyIn0.kEgTRTo1_9bihfEU0OauJf57SZ3o1w3eChOd94xlaGk

{
  "title": "Dune: Special Edition",
  "author": "Frank Herbert",
  "year": 1965,
  "version": "2d512f49-2d26-44f0-8d9c-4d447ace8df4"
}